[aliases]
"alpine" = "docker.io/library/alpine"
"busybox" = "docker.io/library/busybox"
"kindest/node" = "docker.io/kindest/node"
"mysql" = "docker.io/library/mysql"
"nginx" = "docker.io/library/nginx"
"nginxinc/nginx-unprivileged" = "docker.io/nginxinc/nginx-unprivileged"
"oliver006/redis_exporter" = "docker.io/oliver006/redis_exporter"
"prom/prometheus" = "docker.io/prom/prometheus"
"python" = "docker.io/library/python"
"redis" = "docker.io/library/redis"
