"""Shared runtime settings for Toolathlon benchmark evaluation."""

SUBAGENT_CONTEXT_TOKENS = 256_000
SUBAGENT_RECURSION_LIMIT = 410
DECOMPOSER_RECURSION_LIMIT = 410
DEEPSEEK_REASONING_EFFORT = "high"
